version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  osclass:
    image: 'bitnami/osclass:latest'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'osclass_data:/bitnami/osclass'
      - 'apache_data:/bitnami/apache'
volumes:
  mariadb_data:
    driver: local
  osclass_data:
    driver: local
  apache_data:
    driver: local
